@baseUrl=http://localhost:5136/api/Order
@orderId=67252930f91603f6fd19d4cc
@productId=6722bf4aeb48c2736ced6450
@userId=6722cb3ba543f1b390ccc030

### Create Order
POST {{baseUrl}}
Content-Type: application/json

{
  "userId": "{{userId}}",
  "productId": "{{productId}}",
  "quantity": 4,
  "status": "Pending"
}

### Get Order by ID
GET {{baseUrl}}/{{orderId}}
Accept: application/json


### Get Orders by User ID
GET {{baseUrl}}/user/{{userId}}
Accept: application/json


### Update Order Status
PUT  {{baseUrl}}/{{orderId}}
Content-Type: application/json

{
  "userId": "{{userId}}",
  "productId": "{{productId}}",
  "quantity": 3,
  "status": "Not"
}

### Delete Order by order ID
DELETE {{baseUrl}}/{{orderId}}
Accept:  application/json
