@baseUrl=http://localhost:5136/api
@productId=6723e26d1e5fc901fc129c51

### Get All Products
GET {{baseUrl}}/Product
Accept: application/json

### Get Product by ID
GET {{baseUrl}}/Product/{{productId}}
Accept:application/json

### Add Product
POST {{baseUrl}}/Product
Content-Type: application/json

{
  "name": "Bus",
  "description": "32L LG Honda",
  "price": 555.99,
  "instock": 8
}

### Update Product
PUT {{baseUrl}}/Product/{{productId}}
Content-Type: application/json

{
  "productId": "{{productId}}",
  "name": "Samsung HDTV",
  "description": "Amazement on prick.",
  "price": 15500.99,
  "instock": 150
}

### Delete Product
DELETE {{baseUrl}}/Product/{{productId}}
Accept: application/json
